import { inter } from "@/ui/fonts";
import "./globals.css";
import Header from "@/components/header";
import AuthProvider from "@/components/authProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${inter.className} mx-auto px-2 md:max-w-4xl`}>
          <Header session={session} />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
